<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27068" started-at="2021-01-17T20:54:24 CST" finished-at="2021-01-17T20:54:51 CST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27068" started-at="2021-01-17T20:54:24 CST" finished-at="2021-01-17T20:54:51 CST">
      <class name="billingTechFios.MissionTestNG">
        <test-method status="PASS" signature="iniTial()[pri:0, instance:billingTechFios.MissionTestNG@51cdd8a]" name="iniTial" is-config="true" duration-ms="8538" started-at="2021-01-17T20:54:24 CST" finished-at="2021-01-17T20:54:32 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- iniTial -->
        <test-method status="PASS" signature="loginTestA()[pri:0, instance:billingTechFios.MissionTestNG@51cdd8a]" name="loginTestA" duration-ms="5191" started-at="2021-01-17T20:54:32 CST" finished-at="2021-01-17T20:54:38 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestA -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:billingTechFios.MissionTestNG@51cdd8a]" name="tearDown" is-config="true" duration-ms="1416" started-at="2021-01-17T20:54:38 CST" finished-at="2021-01-17T20:54:39 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="iniTial()[pri:0, instance:billingTechFios.MissionTestNG@51cdd8a]" name="iniTial" is-config="true" duration-ms="6680" started-at="2021-01-17T20:54:39 CST" finished-at="2021-01-17T20:54:46 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- iniTial -->
        <test-method status="FAIL" signature="loginTestB()[pri:0, instance:billingTechFios.MissionTestNG@51cdd8a]" name="loginTestB" duration-ms="4228" started-at="2021-01-17T20:54:46 CST" finished-at="2021-01-17T20:54:50 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong Answer expected [Dashboard1] but found [Dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong Answer expected [Dashboard1] but found [Dashboard]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at billingTechFios.MissionTestNG.loginTestB(MissionTestNG.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestB -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:billingTechFios.MissionTestNG@51cdd8a]" name="tearDown" is-config="true" duration-ms="951" started-at="2021-01-17T20:54:50 CST" finished-at="2021-01-17T20:54:51 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- billingTechFios.MissionTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
